name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CHATLUTHIER_PEM }}  # SSH key for accessing the server

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H ec2-13-60-6-122.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts  # Ensure SSH connection works smoothly
      
      - name: Add GitHub's Host Key to Known Hosts on EC2
        run: |
          ssh ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"  # Add GitHub's host key to the server's known hosts
      
      - name: Pull latest code
        run: |
          ssh ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com "cd /home/ec2-user/chatluthier && git pull origin main"

      - name: Restart server
        run: |
          ssh ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com "pm2 restart all"
