name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Using the latest version of the checkout action

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4  # Configure SSH agent
        with:
          ssh-private-key: ${{ secrets.CHATLUTHIER_PEM }}  # Access the SSH key from GitHub Secrets

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H ec2-13-60-6-122.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts  # Add the EC2 host to known hosts

      # Step 3: Clear the target directory on the remote server
      - name: Clear remote directory
        run: |
          ssh ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com "rm -rf /home/ec2-user/chatluthier/assets/*"

      # Step 4: Copy the necessary files to the remote server
      - name: Copy files to remote server
        run: |
          scp -v -r public ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
          scp -v -r assets ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
          scp -v server.js ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
          scp -v credits.json ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
          scp -v package-lock.json ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
          scp -v package.json ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com:/home/ec2-user/chatluthier
      # Step 5: Update server configuration and restart the service
      - name: Update server and restart
        run: |
          ssh ec2-user@ec2-13-60-6-122.eu-north-1.compute.amazonaws.com "cd /home/ec2-user/chatluthier && find . -type f \\( -name '*.js' -o -name '*.html' \\) -exec sed -i 's|http://127.0.0.1:3000|https://chatluthier.org|g' {} \\; && pm2 restart all"