name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CHATLUTHIER_PEM }}  # SSH key for accessing the server

      - name: Add EC2 Host to Known Hosts
        run: |
          ssh-keyscan -H chatluthier.org >> ~/.ssh/known_hosts  # Ensure SSH connection works smoothly
      
      - name: Add GitHub's Host Key to Known Hosts on EC2
        run: |
          ssh ec2-user@chatluthier.org "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"  # Add GitHub's host key to the server's known hosts
      
      - name: Pull latest code
        run: |
          ssh ec2-user@chatluthier.org "cd /home/ec2-user/chatluthier && git fetch && git reset --hard origin/main"

      - name: Change domain
        run: |
            ssh -i chatluthier.pem ec2-user@chatluthier.org "cd /home/ec2-user/chatluthier && find . -type f \( -name '*.js' -o -name '*.html' \) -exec sed -i 's|http://127.0.0.1:3000|https://chatluthier.org|g' {} \; && find . -type f \( -name '*.js' -o -name '*.html' \) -exec sed -i 's|localhost|chatluthier.org|g' {} \; && find . -type f \( -name '*.js' -o -name '*.html' \) -exec sed -i 's|ws://|wss://|g' {} \;"
      - name: Change domain
        run: |
          ssh -i chatluthier.pem ec2-user@chatluthier.org "cd /home/ec2-user/chatluthier && npm install && npm update && npm run build"

      - name: Restart server
        run: |
          ssh ec2-user@chatluthier.org "pm2 restart all"
